[2024-03-10T15:56:59.200+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: price_processing.stage_external_sources manual__2024-03-10T15:56:57.340473+00:00 [queued]>
[2024-03-10T15:56:59.209+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: price_processing.stage_external_sources manual__2024-03-10T15:56:57.340473+00:00 [queued]>
[2024-03-10T15:56:59.210+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2024-03-10T15:56:59.220+0000] {taskinstance.py:1382} INFO - Executing <Task(DbtRunOperationLocalOperator): stage_external_sources> on 2024-03-10 15:56:57.340473+00:00
[2024-03-10T15:56:59.223+0000] {standard_task_runner.py:57} INFO - Started process 262 to run task
[2024-03-10T15:56:59.226+0000] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'price_processing', 'stage_external_sources', 'manual__2024-03-10T15:56:57.340473+00:00', '--job-id', '49', '--raw', '--subdir', 'DAGS_FOLDER/price_dag.py', '--cfg-path', '/tmp/tmpkli1r56q']
[2024-03-10T15:56:59.229+0000] {standard_task_runner.py:85} INFO - Job 49: Subtask stage_external_sources
[2024-03-10T15:56:59.292+0000] {task_command.py:416} INFO - Running <TaskInstance: price_processing.stage_external_sources manual__2024-03-10T15:56:57.340473+00:00 [running]> on host 6d6d8f1b96f5
[2024-03-10T15:56:59.618+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='price_processing' AIRFLOW_CTX_TASK_ID='stage_external_sources' AIRFLOW_CTX_EXECUTION_DATE='2024-03-10T15:56:57.340473+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-03-10T15:56:57.340473+00:00'
[2024-03-10T15:56:59.619+0000] {local.py:202} INFO - Cloning project to writable temp directory /tmp/tmpoca7oe46 from /opt/airflow/dags/dbt/warehouse
[2024-03-10T15:56:59.622+0000] {config.py:253} INFO - Using user-supplied profiles.yml at /opt/airflow/dags/dbt/warehouse
[2024-03-10T15:56:59.625+0000] {subprocess.py:60} INFO - Tmp dir root location: 
 /tmp
[2024-03-10T15:56:59.625+0000] {subprocess.py:73} INFO - Running command: ['/opt/airflow/.local/bin/***', 'deps', '--profiles-dir', '/opt/airflow/dags/***', '--profile', 'warehouse', '--target', 'dev']
[2024-03-10T15:56:59.632+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/cosmos/operators/base.py", line 246, in execute
    self.build_and_run_cmd(context=context, cmd_flags=self.add_cmd_flags())
  File "/home/airflow/.local/lib/python3.10/site-packages/cosmos/operators/local.py", line 370, in build_and_run_cmd
    result = self.run_command(cmd=dbt_cmd, env=env, context=context)
  File "/home/airflow/.local/lib/python3.10/site-packages/cosmos/operators/local.py", line 226, in run_command
    self.run_subprocess(
  File "/home/airflow/.local/lib/python3.10/site-packages/cosmos/operators/local.py", line 189, in run_subprocess
    subprocess_result: FullOutputSubprocessResult = self.subprocess_hook.run_command(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/cosmos/hooks/subprocess.py", line 75, in run_command
    self.sub_process = Popen(
  File "/usr/local/lib/python3.10/subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/local/lib/python3.10/subprocess.py", line 1863, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/.local/bin/dbt'
[2024-03-10T15:56:59.644+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=price_processing, task_id=stage_external_sources, execution_date=20240310T155657, start_date=20240310T155659, end_date=20240310T155659
[2024-03-10T15:56:59.656+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 49 for task stage_external_sources ([Errno 2] No such file or directory: '/opt/airflow/.local/bin/dbt'; 262)
[2024-03-10T15:56:59.698+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2024-03-10T15:56:59.720+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
